"use client";

import {
  useEffect,
  useState,
} from "react";

import FadeUp from "@/components/motion/FadeUp";
import PremiumCard from "@/components/ui/PremiumCard";
import SectionTitle from "@/components/ui/SectionTitle";
import NayankLoader from "@/components/ui/NayankLoader";

import {
  getAlerts,
  markAlertRead,
} from "@/services/alert.services";

export default function Notifications() {
  const [alerts, setAlerts] =
    useState<any[]>([]);

  const [loading, setLoading] =
    useState(true);

  useEffect(() => {
    loadAlerts();
  }, []);

  const loadAlerts =
    async () => {
      try {
        const data =
          await getAlerts();

        setAlerts(data);
      } catch (
        error
      ) {
        console.error(
          error
        );
      } finally {
        setLoading(false);
      }
    };

  const handleRead =
    async (
      id: string
    ) => {
      try {
        await markAlertRead(
          id
        );

        setAlerts(
          alerts.map(
            (alert) =>
              alert.id ===
              id
                ? {
                    ...alert,
                    isRead:
                      true,
                  }
                : alert
          )
        );
      } catch (
        error
      ) {
        console.error(
          error
        );
      }
    };

  if (loading) {
    return (
      <NayankLoader />
    );
  }

  return (
    <div>
      <FadeUp>
        <SectionTitle
          title="Notifications"
          subtitle="Alerts generated by NAYANK."
        />
      </FadeUp>

      {alerts.length ===
      0 ? (
        <PremiumCard>
          <h2>
            No Notifications
          </h2>
        </PremiumCard>
      ) : (
        <div
          style={{
            display:
              "grid",
            gap: "20px",
          }}
        >
          {alerts.map(
            (alert) => (
              <FadeUp
                key={
                  alert.id
                }
              >
                <PremiumCard>
                  <div
                    style={{
                      display:
                        "flex",
                      justifyContent:
                        "space-between",
                      alignItems:
                        "center",
                    }}
                  >
                    <div>
                      <h3>
                        {
                          alert.type
                        }
                      </h3>

                      <p
                        style={{
                          color:
                            "#94A3B8",
                        }}
                      >
                        {
                          alert.message
                        }
                      </p>

                      <small
                        style={{
                          color:
                            "#64748B",
                        }}
                      >
                        {new Date(
                          alert.createdAt
                        ).toLocaleString()}
                      </small>
                    </div>

                    {!alert.isRead && (
                      <button
                        onClick={() =>
                          handleRead(
                            alert.id
                          )
                        }
                        style={{
                          border:
                            "none",
                          cursor:
                            "pointer",
                          padding:
                            "10px 16px",
                          borderRadius:
                            "12px",
                          background:
                            "#2563EB",
                          color:
                            "#fff",
                        }}
                      >
                        Mark Read
                      </button>
                    )}
                  </div>
                </PremiumCard>
              </FadeUp>
            )
          )}
        </div>
      )}
    </div>
  );
}